{{- if .Values.pgadmin.create }}
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
  labels:
    helm.sh/chart: "{{ printf "%s-%s" .Chart.Name .Chart.Version }}"
    app.kubernetes.io/name: pgadmin-svc
    app.kubernetes.io/instance: {{ .Chart.AppVersion }}
spec:
  type: {{ if .Values.local.create }}NodePort{{ else }}LoadBalancer{{ end }}
  selector:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/instance: {{ .Chart.AppVersion }}
  ports:
  - port: {{ .Values.pgadmin.port }}
    {{- if .Values.local.create }}
    nodePort: {{ .Values.pgadmin.port }}
    {{- end }}
    targetPort: http
{{- end }}