apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgdb-sts
spec:
  selector:
    matchLabels:
      app: pgdb
  serviceName: 'pgdb'
  replicas: 1
  template:
    metadata:
      labels:
        app: pgdb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
      priorityClassName: required-preempting-pc
      containers:
      - name: pgdb
        image: "{{ .Values.pgdb.image.repository }}{{ with .Values.pgdb.image.tag }}:{{ . }}{{ end }}"
        imagePullPolicy: {{ .Values.pgdb.image.pullPolicy }}
        ports:
        - containerPort: 5432
          hostPort: 5432
          name: postgres
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: pgdbdata-volume
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
  volumeClaimTemplates:
  - metadata:
      name: pgdbdata-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 32Gi