apiVersion: v1
kind: Service
metadata:
  name: pgdb-svc
  labels:
    helm.sh/chart: "{{ printf "%s-%s" .Chart.Name .Chart.Version }}"
    app.kubernetes.io/name: pgdb-svc
    app.kubernetes.io/instance: {{ .Chart.AppVersion }}
spec:
  {{- if .Values.proxy.create }}
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: cloudsqlproxy
    app.kubernetes.io/instance: {{ .Chart.AppVersion }}
  ports:
  - port: {{ .Values.proxy.port }}
    targetPort: cloudsqlproxy
  {{- end }}
  {{- if .Values.local.create }}
  type: NodePort
  selector:
    app.kubernetes.io/name: pgdb
    app.kubernetes.io/instance: {{ .Chart.AppVersion }}
  ports:
  - port: {{ .Values.local.port }}
    nodePort: {{ .Values.local.port }}
    targetPort: pgsql
  {{- end }}
  {{- if .Values.endpoint.create }}
  type: ClusterIP
  ports:
  - port: {{ .Values.endpoint.port }}
  {{- end }}